README.md

The clevis-bind-luks command has an -d option to specify the LUKS device
to bind to a pin, but it's missing in the README.md example.

README.md: Add a missing -d option to clevis-bind-luks example command

---

Makefile.am
configure.ac
src/Makefile.am
src/dracut/module-setup.sh.in

The tpm2-tools may not be available on some systems, so it shouldn't be
installed unconditionally. Check for the tools before attempting to add
support for the clevis tpm2 pin, both in the system and the initramfs.
Fixes: #26

Don't install clevis tpm2 pin if the tpm2 tools aren't available

---

src/clevis-decrypt-tpm2
src/clevis-encrypt-tpm2

To use the tpm2 pin, some temporary files need to be created due how the
tpm2-tools work. Currently they are created in the user's home directory
but the commands can be executed by a user that doesn't have a home dir.
So it's better to just create the temporary directory in /tmp, which is
mktemp default. The mktemp default permissions are u+rwx anyways, so it
isn't less secure to have the temp dir at /tmp instead of the home dir.
Fixes: #30

Don't attempt to create temporary files in the user's home directory

---

INSTALL.md

This pull request adds a bootstrap script so users don't need to manually call autoreconf with the correct options and an INSTALL.md file that explains how to build from source and the project dependencies.

Make build easier

---

src/clevis-luks-unlock

The loop that tries to open the dm-crypt devices using the pins in the
luksmeta header is executed in a subshell. So on success it calls exit
to exit the subshell.
But then clevis-luks-unlock has no way to know if the encrypted device
was opened correctly or not. So run the loop in the main shell process
and return 0 as exit status if the operation was successful.
Fixes: #36

Don't execute clevis-luks-unlock while loop in a subshell

---

src/clevis

So that things don't silently fail when packages are missing.
Fixes #42

Exit with code 1 when given a unknown sub-command

---

src/clevis-decrypt-http
tests/pin-http

The expected "jwk" variable wasn't set in this case and the actual
decryption would fail with "Invalid key!".

Fix decryption of http with jwk+json type

---

src/clevis-decrypt-tpm2
src/clevis-encrypt-tpm2

The tpm2 pin requires tpm2-tools version 3, so check if the correct
version was installed and exit with an error if that's not the case.
Fixes: #48

Check for compatible tpm2-tools version

---

src/clevis-luks-bind
src/clevis-luks-unbind

Currently the clevis luks commands don't check if the device passed by the
user is a LUKS device or not. So if a wrong dev is used, clevis will just
exit with a status of 1 without giving any indication what went wrong:
$ sudo clevis luks bind -d /dev/sda2 tpm2 '{}'
$ echo $?
1

Make clevis-luks commands to check if the device is LUKS

---

src/clevis-luks-bind
src/clevis-luks-unbind

Clevis only supports the LUKSv1 on-disk format, so is not enough to check
if the device is a LUKS device. Also the format version has to be checked.
Suggested-by: Ondrej Kozina <okozina@redhat.com>

Check if the LUKS on-disk format is v1

---

README.md
src/clevis.1.adoc
src/luks/clevis-luks-bind.1.adoc
src/luks/systemd/dracut/module-setup.sh.in
src/pins/sss/clevis-encrypt-sss.1.adoc

@npmccallum, this pull request contains fixes that fix issues with clevis 11 on Fedora 29.
It has the fixes suggested by @doverride and @fchiacchiaretta in issues #73 and #74 respectively.

Clevis fixes for Fedora 29

---

src/pins/tpm2/clevis-encrypt-tpm2

% git grep pcr_hash
src/pins/tpm2/clevis-encrypt-tpm2:pcr_bank=`jose fmt -j- -Og pcr_hash -u- <<< "$cfg"` || pcr_bank="sha1"
So this is clearly typo and pcr_hash should be pcr_bank

bugfix: set pcr_bank from pcr_bank not pcr_hash field

---

src/luks/systemd/dracut/clevis-pin-tpm2/module-setup.sh.in
src/pins/tpm2/clevis-decrypt-tpm2
src/pins/tpm2/clevis-encrypt-tpm2
src/pins/tpm2/meson.build

A first [release candiate](https://github.com/tpm2-software/tpm2-tools/releases/tag/4.0-rc0) for tpm2-tools 4.0 has been tagged. This is a major release that contains many [backwards-incompatible option name changes and tool renames](https://github.com/tpm2-software/tpm2-tools/blob/c02b68d56f1ce7a67b1be580b7efe128d26447bf/CHANGELOG.md#40-rc0---2019-08-19). This PR adds support for the new version while retaining backwards compatibility with tpm2-tools 3.X by parsing the tpm2-tools version output and switching accordingly.
Closes: #56
Fixes: #117

Add support for tpm2-tools 4.0

---

src/luks/systemd/clevis-luks-askpass
src/luks/systemd/dracut/clevis/module-setup.sh.in

`nc` is assumed to be `ncat` from Nmap for the `--send-only` option to work. This assumption holds true on Fedora, where `nc` is a symbolic link to `ncat`, while other distributions only ship the binary with the original upstream name. Replacing the name makes it clearer which version of `nc` is expected and improves compatibility with other distributions while retaining compatibility with Fedora.
This is an alternative approach to #51, which replaces `nc` by `socat`. In contrast to #51, this PR does not require any dependency changes, see https://github.com/latchset/clevis/issues/74#issuecomment-428975197. `ncat` is available on Arch, Debian/Ubuntu, Fedora, openSUSE and possibly many other distributions I haven't checked (since it is the upstream binary name) and is much less ambiguous …

clevis-luks-askpass: replace nc by ncat

---

src/pins/tang/clevis-encrypt-tang

Sometimes, tang may not generate an advertisement with 'deriveKey' [1],
so let's check whether we have the key derivation key before proceeding
to encryption.
Original patch by D. Kopecek.
[1] Related to https://github.com/latchset/tang/issues/23

pins/tang: check that key derivation key is available

---

src/luks/clevis-luks-bind.in
src/luks/clevis-luks-unbind.in
src/luks/clevis-luks-unlock.in
src/luks/meson.build

* Ubuntu 18.04 LTS ships with v2.02, so by default builds of clevis on
Ubuntu 18.04 will not configure the luks modules. Downgrading to
2.02 doesn't seem to remove too much in the way of functionality and
ensures that 18.04 can use clevis for automated disk unlocking.
* Make use of LUKSv2 tokens conditional. In order to support older
distrobutions (running cryptsetup < 2.0.4) stick with using
luksv1/luksmeta unless v2.0.4 or higher is detected.
Re-opening due to github weirdness.

Compat: Downgrade cryptsetup dependency to v2.0.2

---

src/luks/udisks2/meson.build

Compilation in a minimal container fails with the non-helpful:
```
include <udisks/udisks.h>
^~~~~~~~~~~~~~~~~
compilation terminated.
[5/8] Compiling C object 'src/pins/sss/1b1ef4e@@clevis-encrypt-sss@exe/sss.c.o'.
ninja: build stopped: subcommand failed.
```
This is a confusing message though because even installing `libudisks2-dev`
doesn't fix it.
It's actually `pkg-config` throwing up failures:
```
$ /usr/bin/pkg-config --cflags udisks2
Package gio-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gio-2.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gio-2.0', required by 'udisks2', not found
```
So the `gio-2.0` dependency is missing.  This can be fixed on Ubuntu or Debian
by installing `libglib2.0-dev`.
So make that a real …

trivial: fix non-obvious compilation problems on Ubuntu 19.04 (Fixes: #126)

---

README.md
src/initramfs-tools/hooks/clevis.in
src/initramfs-tools/hooks/meson.build
src/initramfs-tools/meson.build
src/initramfs-tools/scripts/local-bottom/clevis.in
src/initramfs-tools/scripts/local-bottom/meson.build
src/initramfs-tools/scripts/local-top/clevis.in
src/initramfs-tools/scripts/local-top/meson.build
src/initramfs-tools/scripts/meson.build
src/meson.build

The original author of #35 hasn't responded to a ping on their request - I'd be happy to help push this along. These changes are based on #35 - rebased against the current master, and ported to meson. I haven't had a chance to test an Ubuntu system yet, but it seems to build.
I'm in the process of setting up a test environment, but I figured I would create the PR first to get some early feedback, should the author of the original PR resurface I'm happy to have this one closed/marked as dupe.
-----
Added ports to initramfs-tools based systems.
* src/initramfs-tools/hooks/clevis.in: New file.
* src/initramfs-tools/hooks/meson.build: New file.
* src/initramfs-tools/scripts/local-bottom/clevis.in: New file.
* src/initramfs-tools/scripts/local-bottom/meson.build: New file.
* …

Support for initramfs-tools based unlocker (Debian/Ubuntu)

---

src/luks/meson.build
src/luks/tests/bind-luks1
src/luks/tests/bind-luks2
src/luks/tests/bind-wrong-pass-luks1
src/luks/tests/bind-wrong-pass-luks2
src/luks/tests/meson.build
src/luks/tests/tests-common-functions.in
src/luks/tests/unbind-luks1
src/luks/tests/unbind-luks2
src/luks/tests/unbind-unbound-slot-luks1
src/luks/tests/unbind-unbound-slot-luks2

Right now a couple of tests that includes binding fail when running
in a system with old (< 2.0.4) cryptsetup.
Once we have travis-ci integrated, it will be simpler to make sure
common cases are working.

Add tests for LUKS binding and unbinding

---

src/luks/clevis-luks-bind.in
src/luks/tests/bind-key-file-non-interactive-luks1
src/luks/tests/bind-pass-with-newline-keyfile-luks1
src/luks/tests/bind-pass-with-newline-luks1
src/luks/tests/meson.build
src/luks/tests/tests-common-functions.in

We now use cryptsetup and key file, and that way we handle
passphrases with newlines on them as well.
Add also tests to confirm non-interactive mode is working.
Fixes: #105

Rework the logic for reading the existing key

---

src/luks/clevis-luks-bind.in

Below is the output of the `cryptsetup luksAddKey` command on Ubuntu 18.04 running cryptsetup v2.0.2:
`$ cryptsetup --version
cryptsetup 2.0.2`
`$ sudo cryptsetup luksAddKey -v /dev/vg1/lv1  < <(echo "myPassphrase"; echo -n "newKey")`
`Key slot 0 unlocked.`
`Key slot 0 unlocked.`
`Command successful.`
My change accommodates the use of '`unlocked`' vs, '`created`' as well as the fact that two identical lines are output.  
Additionally, errors can occur at line 142 without being passed on, therefore, I've added a 2nd if/then catch for a case when `SLT` does not get properly assigned a value by this point.

fix for different output from 'luksAddKey' command w/cryptsetup v2.0.2

---

src/luks/clevis-luks-bind.in
src/luks/tests/bind-already-used-luksmeta-slot
src/luks/tests/meson.build

In some situations, especially with older versions of clevis, we can end
up with a partially used luksmeta slot.
We can identify such slots because they will be marked as inactive, yet
they will contain the clevis UUID, "cb6e8904-81ff-40da-a84a-07ab9ab5715e".
When this situation happens, we have cryptsetup and luksmeta slots "out
of sync", and since we currently have cryptsetup choose the slot, we may
end up trying to use such a partially used slot, which in turn will fail
because luksmeta will not be able to save data to it.
We handle this case by wiping the partially used slot, if we identify
the situation will arise.
Tests also added to verify this case is handled properly.
Fixes: #70

Handle case where we try to use a partially used luksmeta slot

---

src/initramfs-tools/scripts/local-top/clevis.in

I did testing with master on Ubuntu 20.04 daily images and found some lacking aspects for LUKS2.  I ported some stuff over from the systemd script to work in the initramfs-tools one.
I confirmed this works properly with FDE on Ubuntu 20.04.

initramfs: Add support for LUK2

---

src/pins/tpm2/clevis-decrypt-tpm2
src/pins/tpm2/clevis-encrypt-tpm2
src/pins/tpm2/meson.build
src/pins/tpm2/pin-tpm2

As of now, our parsing of pcr_ids fails if we try to use an actual JSON
array, and when it happens, we end up silently using no policy at all,
which is certainly not what the user requested/intended.
This patch improves our parsing to support reading both strings and JSON
arrays for the pcr_ids propery. If we encounter an error, we report it
and exit.
Fixes: #103

Validate the pcr_ids and error out if parsing fails

---

src/initramfs-tools/scripts/local-top/clevis.in

Some "do" statements with data piped to them were on new lines and further indented. While the formatting was consistent, this brought the actual "do" statement an indentation further in than its corresponding "done" statement making the termination of the code segment ambiguous. Removed these line breaks to improve readability.

Readability Fix: "do" statement indentation offset from "done"

---

src/pins/tpm2/clevis-encrypt-tpm2
src/pins/tpm2/pin-tpm2

In PR#140 we improved the validation for pcr_ids, however we introduced
an error in this validation, which broke cases in which we specify
something in the configuration, but not the pcr_ids attribute.
E.g.: '{"key": "ecc"}' now fails with "Parsing the requested policy
failed!".
In this commit we fix this issue and add a new test case to cover it.

tpm2: fix pcr_ids validation

---

src/initramfs-tools/scripts/local-top/clevis.in

While testing clevis-initramfs on an Ubuntu 20.04 system, I observed
the following (w/ set -x enabled):
+ '[' -p /usr/lib/cryptsetup/passfifo ']'
++ grep -z '^CRYPTTAB_SOURCE=' /proc/395/environ
grep: invalid option -- 'z'
BusyBox v1.30.1 (Ubuntu 1:1.30.1-4ubuntu5) multi-call binary.
Usage: grep [-HhnlLoqvsriwFE] [-m N] [-A/B/C N] PATTERN/-e PATTERN.../-f FILE [FILE]...
While the busybox package does support 'grep -z', the busybox-initramfs
package does not. Use tr to do the NULL conversion instead.

Avoid grep -z, which isn't supported by busybox-initramfs

---

src/initramfs-tools/scripts/local-top/clevis.in

I refactored a bunch of this to support failures so that we could retry. The problem in my environment is we are using tang and if the tang service was unavailable, this would just exit out. Now with these modifications, it will sit and attempt to retry every 5 seconds. Besides that, I made the PATHFIFO support dynamic so it works on 18.04 and 20.04 (tested both), and hopefully, all others going forward since it isn't so rigid.
Most of the moving to functions were so that we could properly handle error code returns and loop. My testing here is 100% limited to typing in passwords and tang + tang failure+resurrection. I have not used other methods but given the scope of how the code was originally written it shouldn't be impacted but I would love to have somebody validate that.

Updated initramfs-tools to work on 18.04 and 20.04 - also made it retry

---

.travis/install
.travis/script

- Use dnf builddep for installing Fedora dependencies
- export DEBIAN_FRONTEND variable for Debian/Ubuntu
- retry when uploading coverage info

Updates to travis CI

---

.travis/install
README.md
src/luks/clevis-luks-common-functions
src/luks/clevis-luks-list
src/luks/clevis-luks-list.1.adoc
src/luks/meson.build
src/luks/tests/list-recursive-luks1
src/luks/tests/list-recursive-luks2
src/luks/tests/list-sss-tang-luks1
src/luks/tests/list-sss-tang-luks2
src/luks/tests/list-tang-luks1
src/luks/tests/list-tang-luks2
src/luks/tests/meson.build
src/luks/tests/tests-common-functions.in

Reviving Javier's idea in PR#24, we now have a command to list the pins
bound to a LUKS volume.
Usage:
clevis luks list -d DEV [-s SLT]
Examples:
clevis luks list -d device
1: sss '{"t":1,"pins":{"tang":[{"url":"addr1"},{"url":"addr2"}],"tpm2":[{"hash":"sha256","key":"ecc"}],"sss":{"t":1,"pins":{"tang":[{"url":"addr3"}]}}}}'
2: tang '{"url":"addr"}'
3: tpm2 '{"hash":"sha256","key":"ecc","pcr_bank":"sha1","pcr_ids":"7"}'
clevis luks list -d device -s 3
3: tpm2 '{"hash":"sha256","key":"ecc","pcr_bank":"sha1","pcr_ids":"7"}'

Add clevis luks list command

---

README.md
src/clevis.1.adoc
src/luks/clevis-luks-bind.1.adoc
src/luks/clevis-luks-list.1.adoc
src/luks/clevis-luks-unbind.1.adoc
src/luks/clevis-luks-unlock.1.adoc
src/pins/sss/clevis-encrypt-sss.c

- Remove reference to `http` pin in `clevis-encrypt-sss`
- Updates to README and man pages, which were referring to LUKSv1 as the only supported

Misc fixes

---

src/initramfs-tools/scripts/local-top/clevis.in

The askpass pid we've found may exit before we try to read its environ
file. When that happens, we'll see some ugly messages on the console:
/scripts/local-top/clevis: line 135: local: `': not a valid identifier
/scripts/local-top/clevis: line 135: /proc/361/environ: No such file or directory
/scripts/local-top/clevis: line 135: local: `': not a valid identifier
/scripts/local-top/clevis: line 135: /proc/361/environ: No such file or directory
/scripts/local-top/clevis: line 135: local: `': not a valid identifier
/scripts/local-top/clevis: line 135: /proc/361/environ: No such file or directory
/scripts/local-top/clevis: line 135: local: `': not a valid identifier
Avoid this by using cat to read the file and prevent it from emitting an error
to the console if the /proc file has vanished by …

initramfs: Avoid noise due to /proc race

---

src/pins/tpm2/clevis-encrypt-tpm2
src/pins/tpm2/pin-tpm2

Configurations like '"pcr_ids": "0, 1"}' were failing because we
did not properly parse the PCR IDs.
Quick test:
echo foo | clevis encrypt tpm2 '{"pcr_ids": "0, 1"}' | clevis decrypt
Unsealing jwk from TPM failed!

tpm2: fix parsing when there are spaces in the list of PCR IDs

---

src/luks/systemd/clevis-luks-askpass.path
src/luks/systemd/clevis-luks-askpass.service.in
src/luks/systemd/dracut/clevis-pin-tang/module-setup.sh.in

Hi,
While integrating Clevis into Fedora CoreOS and RHCOS, we've encountered problems with the way the dracut modules and Clevis units pull in networking targets. These problems are not unique to FCOS/RHCOS (see e.g. #54 and #206). This patch series fixes these dependencies to better conform to the systemd and dracut models. The most important commits in this patch series are the first two:
```
commit 088be96472a234b9368a437078582e8446fffc73
Date:   Thu Jul 2 11:08:55 2020 -0400
systemd: drop hard requirement on networking
Whether we need networking or not for unlocking an encrypted block
device is a property of the block device in question. This is expressed
in `/etc/crypttab` via the `_netdev` option. For example, the systemd
cryptsetup generator[1] picks up on this and correctly orders …
```

Drop hard requirement on networking

---

INSTALL.md

As mentioned in #116, without ncat installed, clevis-luks-askpass cannot write to the socket defined in the _/run/systemd/ask-password/ask.*_ files.

Document ncat dependency in INSTALL.md

---

src/luks/tests/tests-common-functions.in

pin_cfg_equal() was assigning the same value for both configurations
passed as parameters. Fix this and also remove the dependency on the
command diff, as we can compare the JSON value in the variables
directly.
This should also fix the CI failure in some platforms where we do not
have diff installed.

luks: fix comparison of pin configurations in tests

---

src/luks/udisks2/clevis-luks-udisks2.c

So that the process will have correct group access when recovering the
key.

udisks2: call initgroups() before setgid/setuid

---

src/luks/systemd/dracut/clevis/module-setup.sh.in

In general, when possible it's better to use systemd units instead of
dracut hooks because it's (not surprisingly) easier to integrate with
other systemd units in the initramfs.
Let's do our part towards eventually phasing out the "init system within
an init system" situation we're in right now and prefer systemd units on
systemd-based initrds.
It also mirrors how unlocking works in the real root.
You can see this similar "don't ship hooks on systemd" pattern in other
dracut modules (for example `04watchdog`, `50plymouth`, and `90crypt`).

 dracut: favour systemd units over dracut hooks 

---

src/initramfs-tools/scripts/local-top/clevis.in

If the user doesn't provide an ip= command line, configure_networking()
will try to configure each interface until one succeeds. But the one that
configures fastest may not be the one that can communicate with our server.
If we detect a situation where there are multiple configurable NICs and no
ip= parameter, emit a warning so that the user considers this as a possible
reason for failure.

initramfs: Warn if it's not clear which nic to configure

---

src/luks/tests/bad-sss
src/luks/tests/meson.build
src/pins/sss/clevis-encrypt-sss.c
src/pins/sss/meson.build
src/pins/sss/pin-sss
src/pins/tang/meson.build

clevis-encrypt-sss would return 0 (and a JWE, without the pins that failed)
even if the encryption operation failed, when using the sss pin, such as:
echo test | clevis encrypt sss '{"t":1, "pins":{"tang":[{"url":"foo bar"}]}}'
Unable to fetch advertisement: 'foo bar/adv/'!
eyJhbGciOiJkaXIiLCJjbGV2aXMiOnsicGluIjoic3NzIiwic3NzIjp7Imp3ZSI6WyIiXSwicCI6Inlqald0bkM2ZkwtNDhIbTd5Yy1fVmlwWWxTTHZ1ZlliZnRaejFjLW5ucU0iLCJ0IjoxfX0sImVuYyI6IkEyNTZHQ00ifQ..rM6IMXjNIN3uybW1.J5jAtiU.61x_fjXJC1uCjljTnkkdCw
echo $?
0
This is particularly problematic when using clevis luks bind, as it would
appear the operation succeeded, while in practice it did not, which
means we would be unable to unlock this device. E.g.:
clevis luks bind -d device sss '{"t":1, "pins":{"tang":[{"url":"foo bar"}]}}' <<< password
Unable …

pins: improve error reporting for sss pin

---

src/luks/clevis-luks-common-functions
src/luks/clevis-luks-unlockers.7.adoc
src/luks/systemd/clevis-luks-askpass
src/luks/systemd/dracut/clevis/module-setup.sh.in

clevis-luks-askpass has been refactored so that it becomes both
simpler and more reliable.
We now get the list of devices to be unlocked from crypttab, which
makes it simpler to verify whether there are any devices pending to
be unlocked. This improves the reliability in the situation when we
want to unlock multiple devices.
Also, remove the suggestion to add _netdev to crypttab/fstab, as that
is no longer required and in practice could be problematic in many
situations, as it would create dependencies from units to be mounted
during the boot process.
To set up multiple LUKS devices to be unlocked during the boot process,
do the following:
1) create clevis bindings for all the devices
2) run dracut -f to update the initramfs
3) enable clevis-luks-askpass.path unit (systemctl enable …

systemd: rework clevis-luks-askpass for improved reliability

---

src/luks/systemd/clevis-luks-askpass

Especially when running in early boot, clevis-luks-askpass may be
looping because e.g. we still have devices remaining to unlock, as
per crypttab, or we were unable to determine if there are any devices
left to be unlocked.
Eventually we may receive a SIGTERM, from e.g. systemd and we should
exit cleanly in this situation.

systemd: clevis-luks-askpass: exit cleanly with SIGTERM

---

src/initramfs-tools/scripts/local-top/clevis.in

eth_check() currently tries to "link up" each NIC it finds until one is
successful. However, just because it has a link doesn't mean it is the
correct one to use. In fact, the correct interface may not even have been
enumerated yet.
Call a new wait_for_device() function that checks if a user has specified
the correct interface via the ip= command line argument. If so, busy wait
for up to 10s until that device appears. If the user did not specify
an interface, then make a best effort attempt to wait for all devices
to be discovered by calling wait_for_udev(). This will wait for the
udev event queue to empty, which usually means all NICs have been
enumerated. Though it is possible for the event queue to clear temporarily
before the desired NIC is enumerated - we've seen this with some …

initramfs: Wait for interface to appear before attempting configuration

---

src/luks/clevis-luks-bind.1.adoc
src/luks/clevis-luks-bind.in
src/luks/tests/bind-luks2

Currently, when interacting with LUKS2 volumes, my workflow involves using a static token ID and using this static ID to determine the keyslot by reading the `keyslots` key from the token. Given that knowing the keyslot number is required for unbinding, adding this parameter would allow me to determine the keyslot deterministically from the token slot that I've assigned it to. This PR allows users to specify a token ID when binding to a LUKS2 volume so that the token ends up under that ID. Does this sound like something you'd be willing to accept?

Allow user to specify token ID when binding

---

src/luks/systemd/clevis-luks-askpass.service.in

Let's use `Type=simple` since `clevis-luks-askpass -l` is long-running
and not "one-shot".
Noticed this while debugging something else. It doesn't make any
practical difference but could in the future. With `oneshot`, the
service will be stuck in `activating` which means that systemd won't be
able to start any follow-up services which explicitly do
`After=clevis-luks-askpass.service`.

clevis-luks-askpass.service: use Type=simple

---

src/luks/clevis-luks-bind.1.adoc
src/luks/clevis-luks-bind.in
src/luks/tests/assume-yes
src/luks/tests/assume-yes-luks2
src/luks/tests/meson.build
src/pins/sss/clevis-encrypt-sss.1.adoc
src/pins/sss/clevis-encrypt-sss.c
src/pins/tang/clevis-encrypt-tang
src/pins/tang/clevis-encrypt-tang.1.adoc

In order to simplify automated operations with e.g. ansible,
it would be helpful to have a way to automate the creation of
bindings with clevis.
In simple scenarios, it's possible to download the advertisement
from a tang server and pass it in the binding configuration, to
do the binding offline, in the following way:
curl -sfg http://tang.server/adv -o adv.jws
clevis luks bind -d /dev/sda2 tang '{"url":"http://tang.server", "adv":"adv.jws}'
However, for more complex scenarios using multiple servers with
the sss pin, it becomes a lot more complicated to do the same
thing and do the binding in an automated fashion. An alternative
would be to use expect (tcl), but it can also be complicated.
In this commit we introduce -y as a parameter meaning _assume yes_.
Essentially, this would make it …

 Introduce -y (assume yes) argument to clevis luks bind

---

src/luks/systemd/clevis-luks-askpass.path

The current condition was have for watching systemd's ask-password
directory is `PathChanged', which means clevis-luks-askpass would
activate whenever the watched directory changed [1].
However, it is possible that the watched directory is already populated
with ask.xxxx files when clevis-luks-askpass tries to start, in which
case it won't do so, because the condition on the watched directory
won't match. With clevis-luks-askpass not starting, it means that
devices that are bound by clevis won't be unlocked either, as was
reported in [2].
This commit changes the condition on the watched [Path] to the same one
used by both:
- systemd-ask-password-console.path and
- systemd-ask-password-plymouth.path
which are units that handle ask.XXXX ask-password files, similar to
clevis-luks-askpass. …

askpass: change systemd directory watch condition to DirectoryNotEmpty

---

src/luks/clevis-luks-common-functions
src/luks/clevis-luks-regen
src/luks/clevis-luks-regen.1.adoc
src/luks/meson.build
src/luks/tests/backup-restore-luks1
src/luks/tests/backup-restore-luks2
src/luks/tests/meson.build
src/luks/tests/regen-inplace-luks1
src/luks/tests/regen-inplace-luks2
src/luks/tests/regen-not-inplace-luks1
src/luks/tests/regen-not-inplace-luks2
src/luks/tests/tests-common-functions.in

`clevis luks regen` can be used to rotate bindings, for example rotating
tang keys.
General usage is the following: clevis luks regen [-q] -d DEV -s SLT
The above command will regenerate the binding in DEV:SLT.
Tests and man pages added as well.

luks: add clevis luks regen command

---

src/luks/clevis-luks-report
src/luks/clevis-luks-report.1.adoc
src/luks/meson.build
src/luks/tests/meson.build
src/luks/tests/report-sss-luks1
src/luks/tests/report-sss-luks2
src/luks/tests/report-tang-luks1
src/luks/tests/report-tang-luks2

`clevis luks report` is able to identify whether the keys have been
rotated in the server, making it easier to also rotate them in the
clients with the help of `clevis luks regen`.
Usage: `clevis luks report [-r] [-q] -d DEV -s SLT`
The above command will check whether the binding in DEV:SLT had its
keys rotated. If -r is given, it will also run the following, to
rotate the binding, in case it needs rotating:
`clevis luks regen -q -d DEV -s SLT`

luks: add clevis luks report

---

src/luks/clevis-luks-edit
src/luks/clevis-luks-edit.1.adoc
src/luks/meson.build
src/luks/tests/edit-tang-luks1
src/luks/tests/edit-tang-luks2
src/luks/tests/meson.build

`clevis luks edit` can be used to edit an existing binding, e.g., with
tang pins, one is able to edit and modify the URL address -- other pins
allow changing different attributes.
General usage is the following: `clevis luks edit -d DEV -s SLT`
The above command will edit the binding in DEV:SLT.
Tests and man page added as well.

luks: add clevis luks edit command

---

src/luks/clevis-luks-common-functions
src/luks/systemd/dracut/clevis-pin-tang/module-setup.sh.in

Following c52caeb4 (dracut: drop rd.neednet=1 injection), we do not
automatically inject rd.neednet=1 to dracut's cmdline anymore, to
better support generic initrds.
However, when building host-specific initrds and specifying the
--hostonly-cmdline switch we will now add rd.neednet=1 *if* there
are any tang bindings in the devices listed in crypttab.

dracut: add rd.neednet for hostonly-cmdline and tang bindings present

---

src/pins/tpm2/clevis-decrypt-tpm2
src/pins/tpm2/clevis-encrypt-tpm2

A release candidate for tpm2-tools 5.0 [has been tagged](https://github.com/tpm2-software/tpm2-tools/releases/tag/5.0-rc0). Since we explicitly check the major version of the tools (to support the incompatible versions 3.X and 4.X), the allowed version range needs to be expanded.
tpm2-tools 5.0 consolidates all tools into a single busybox-style binary, so the preferred way to invoke the commands would be e.g. `tpm2 createprimary` instead of `tpm2_createprimary`. However, compatibility symlinks `tpm2_*` → `tpm2` are installed by default, so we keep the old syntax for tpm2-tools 5.0 to avoid creating another special case, since the option syntax has not changed (it should be stable since version 4).
tpm2-tools 3.X is deprecated, but unfortunately still packaged by a few Linux distributions, …

pins/tpm2: add support for tpm2-tools 5.X

---

src/pins/tang/clevis-encrypt-tang
src/pins/tang/tests/meson.build
src/pins/tang/tests/tang-common-test-functions.in
src/pins/tang/tests/tang-validate-adv

When performing a bind using the tang pin, we use an advertisement
either obtained from the tang server or passed by in the tang
configuration itself.
If this advertisement is not valid, i.e., not valid JSON, sometimes we
may leak out jose error messages in stderr, which makes the output very
confusing.
Example output would be the following:
Invalid json!
Usage: jose fmt [OPTIONS]
Converts JSON between serialization formats
-X --not Invert the following assertion
-O --object Assert TOP to be an object
-A --array Assert TOP to be an array
-S --string Assert TOP to be a string
-I --integer Assert TOP to be an integer
[...]
In this commit we improve the validation of the advertisement to be used
and also make sure we don't leak raw jose output in the error messages.
Resolves: #259

pins: tang - improve advertisement validation on bind

---

INSTALL.md
src/luks/systemd/clevis-luks-askpass.in
src/luks/systemd/dracut/clevis/module-setup.sh.in
src/luks/systemd/meson.build

When using systemd, i.e., clevis-luks-askpass, we use ncat to send
the decrypted password to the systemd socket as per systemd's password
agents specification [1].
However, systemd itself has a utility that does exactly that,
systemd-reply-password.
In this commit we drop the ncat dependency and instead use
systemd-reply-password in clevis-luks-askpass.
Resolves: #258 
[1] https://systemd.io/PASSWORD_AGENTS/

systemd: drop ncat dependency

---

src/luks/tests/assume-yes

Else the test will trigger messages like
src/luks/tests/assume-yes: line 71: [foo: command not found

Add spaces ot [ invocation in "assume-yes" test

---

src/clevis-decrypt
src/luks/clevis-luks-unlock
src/pins/tang/clevis-decrypt-tang
src/pins/tpm2/clevis-decrypt-tpm2

The <(command) notation in bash relies on the existence of /dev/fd/X,
these device nodes however are no longer created by udev/systemd and
therefore are not available in early userland, breaking unlocking.
Work around by re-writing the code using pipe.
systemd commit:
https://github.com/systemd/systemd/commit/6b2229c6c60d0486
Debian bug report:
https://bugs.debian.org/968518
Closes: #262

Work around /dev/fd/X removal in systemd

---

src/luks/clevis-luks-bind
src/luks/clevis-luks-common-functions.in
src/luks/tests/tests-common-functions.in

This fixes the problem with passwords that contain spaces at beginning or ending. Such a password will make the `existing_key` variable has an incorrect key and result into a "No key available with this passphrase.` or "Nothing to read on input." error.

clevis-luks-bind: Fix error with password of spaces

---

.github/workflows/build.yml

This fixes the auto test always succeeding due to the `cat` making fail return code being ignored.

ci: correct failing logic

---

src/luks/clevis-luks-common-functions.in

This gives the same result without the added dep.
Hit this in FCOS where we don't currently ship `seq` in the initramfs
(normally, the clevis dracut module should've installed it if it
requires it). We could do that of course, but it's even better if we can
avoid it entirely.

luks: replace `seq` with bash's builtin sequence expression

---

src/initramfs-tools/scripts/local-top/clevis.in

There is a separate askpass process (with its own PID) for each encrypted device. So re-get the askpass PID with each loop iteration.
This seems like a hacky fix, but "if it's stupid, but it works, then it ain't stupid"

Fix issue with multiple encrypted devices.

---

.github/workflows/install-dependencies
src/luks/tests/meson.build

Additionally, also check for it in `luks/tests/meson.build`, as it is required for running the tests.

Add cryptsetup as a build dependency in CI for Fedora

---

src/luks/clevis-luks-unlock
src/luks/clevis-luks-unlock.1.adoc

Hello! Currently we're looking for a way to test that a given Clevis token can successfully unlock a crypt device without actually activating the device. Does this seem like something you'd be willing to incorporate upstream?

Add test option for clevis luks unlock

---

src/luks/clevis-luks-common-functions.in
src/pins/tang/clevis-decrypt-tang
src/pins/tang/clevis-encrypt-tang
src/pins/tang/tests/default-thp-alg
src/pins/tang/tests/meson.build

During the encryption using tang, the clevis metadata stores the
thumbprint of the exchange key in the `kid' attribute. This thumbprint
uses jose default thumbprint hash algorithm -- SHA1 as of now.
When decrypting, we validate that the key with thumbprint represented by
`kid' is present in the advertisement. At this point, jose then uses its
default hash algorithm to do the checking. If jose default thumbprint
hash algorithm changes and we have a different default than what was used
to calculate `kid' at encryption time, this verification will fail, and
so does the decryption itself.
To handle a possible change in jose default thumbprint hash algorithm,
this verification was extended to try out every jose supported hash
algorithms, if the validation of `kid' fails with the default one.

tang: default JWK thumbprint is now SHA-256 / deprecate SHA-1

---

src/pins/tang/clevis-encrypt-tang
src/pins/tang/tests/default-thp-alg

After #264, we have started using SHA-256 for the JWK thumbprints,
however an issue was introduced causing clevis to output data to stdout
in certain situations which in turn would render the output of the
encryption malformed.
This commit fixes this issue and updates the tests to catch this
scenario.
Fixes: #304

tang: fix clevis-encrypt-tang when specifying a SHA-256 thp

---

src/luks/clevis-luks-common-functions.in
src/luks/clevis-luks-edit
src/luks/systemd/dracut/clevis/module-setup.sh.in
src/pins/tpm2/clevis-decrypt-tpm2
src/pins/tpm2/clevis-encrypt-tpm2

Sometimes `TMPDIR` may be defined to some non-existing directory, so we
now attempt an `mkdir -p` on it (or `/tmp`, if it's not defined) before
doing an `mktemp` call, in order to minimize the failures when we have
these weird corner cases.

Improve handling of temporary directories

---

src/pins/sss/sss.c

Different OpenSSL versions define BN_zero() differently -- sometimes
returning an integer, sometimes as void --, so let's use instead
BN_set_word() instead, not to have issues when building with these
different versions.

sss: use BN_set_word(x, 0) instead of BN_zero()

---

src/luks/clevis-luks-unbind.in
src/luks/tests/tests-common-functions.in
src/luks/tests/unbind-luks2

When using clevis-luks-unbind against a slot
that has no clevis token assigned, removing the slot
must be avoided.  Fixes #183
Signed-off-by: Sergio Arroutbi Braojos <sarroutb@redhat.com>

Do not kill non clevis slots

---

src/luks/tests/tests-common-functions.in

Older cryptsetup had a different default value for the key size,
e.g. 256, whereas newer ones have changed it to 512.
Let's specify the key size when creating our LUKS devices for the
tests, to make the devices more similar even when running in older
versions of cryptsetup.
We now use 512 as the key size for our test devices.

test: define the key size for our tests

---

src/pins/tpm2/clevis-encrypt-tpm2
src/pins/tpm2/pin-tpm2

After parsing the PCR IDs, validate the combination of pcr_bank and
the PCRs, so that we can better handle invalid situations.
Also update our tpm2 tests to skip some tests if the configuration is
not valid.
Fixes: #327

tpm2: improve validation of PCRs in clevis-encrypt-tpm2

---

src/pins/tpm2/clevis-decrypt-tpm2
src/pins/tpm2/clevis-encrypt-tpm2

This is a way to customize TPM used for clevis binding/unbinding.
For example for tests against a TPM software emulator:
TPM2TOOLS_TCTI=swtpm clevis encrypt tpm2 '{}' <<< 'hello, world'
Closes #244

Reuse system TPM2TOOLS_TCTI envvar if it is set

---

src/pins/sss/sss.h

sss.h: Added include so pid_t type is correctly defined.

---

.github/workflows/build.yml

We will still attempt to build and run these two, but in case they
fail, the CI pipeline will not fail and cancel the other jobs.

ci: make ubuntu:devel and fedora:rawhide not to fail the pipeline

---

src/luks/systemd/dracut/clevis-pin-tpm2/module-setup.sh.in
src/pins/tpm2/meson.build

This is required as c6fc63fc055c18927decc7bcaa07821d5ae37614 added the binary to the decrypt scripts.

Verify that tpm2_flushcontext is installed and added to initramfs

---

src/luks/clevis-luks-common-functions.in

When reading /etc/crypttab in `clevis_devices_to_unlock()`, ignore empty
lines and lines which begin with the '#' char, per crypttab(5).  At
best, it's wasteful to parse these lines.  At worst, we could unlock a
device which was not intended to be unlocked.
Another effect of this is that `clevis-luks-askpass` never exits, it
runs every 500ms, parsing /etc/crypttab in a vain attempt to wait for a
device which may never appear.  The loop in `clevis_devices_to_unlock()`
looks like:
while read -r _ crypt_device _; do
if ! dev=$(clevis_map_device "${crypt_device}") \
|| [ -z "${dev}" ]; then
clevis_devices="${clevis_devices} ${dev}"
continue
fi
...
done
The resulting `${clevis_devices}` grows an empty space for each of the
commented entries where a device is unable to be found.  The loop in …

luks: ignore empty & comment lines in crypttab

---

src/initramfs-tools/hooks/clevis.in

On debian `/usr/bin/which` results in deprecated messages, recommending
`command -v` instead.
They look like:
```
at 10:35:36 ❯ sudo update-initramfs -u -k 'all'
update-initramfs: Generating /boot/initrd.img-5.15.0-2-amd64
I: The initramfs will attempt to resume from /dev/dm-2
I: (/dev/mapper/sys-swap)
I: Set the RESUME variable to override this.
/usr/bin/which: this version of `which' is deprecated; use `command -v' in scripts instead.
/usr/bin/which: this version of `which' is deprecated; use `command -v' in scripts instead.
/usr/bin/which: this version of `which' is deprecated; use `command -v' in scripts instead.
/usr/bin/which: this version of `which' is deprecated; use `command -v' in scripts instead.
/usr/bin/which: this version of `which' is deprecated; use `command -v' in scripts …
```

Use `command -v` instead of `which`

---

src/luks/clevis-luks-common-functions.in

In `clevis_devices_to_unlock()` we use `${clevis_devices}` to track the
devices which need to be processed.  When we are unable to get the
device, we add it to the list and try to activate on a subsequent trip
through the loop.
Use `${crypt_device}` rather than `${dev}` as the latter may well be
empty.  This crept in with the refactoring in 7c17448 (systemd: rework
clevis-luks-askpass for improved reliability, 2020-08-26).
Sergio confirmed that `${crypt_device}` was the intended variable in
response to the question in 0589c14 (luks: ignore empty & comment lines
in crypttab, 2021-11-03)¹.
¹ https://github.com/latchset/clevis/pull/355#pullrequestreview-843477229

luks: fix typo when adding a pending device

---

src/pins/tang/clevis-decrypt-tang

When clevis can not find a remote server when using sss pin, message _Error communicating with the server!_ is dumped
This change dumps the problematic URL, dumping _Error communicating with server http://10.0.139.4_

sss pin: unavailable address should be dumped when one of the URLs is not reachable

---

src/initramfs-tools/hooks/clevis.in

tpm2_flushcontext is not copied over to initramfs but are used in [clevis-decrypt-tpm2 ](https://github.com/latchset/clevis/blob/f5786d3b4b3c282dfea4e29c96601473510886f5/src/pins/tpm2/clevis-decrypt-tpm2#L148)

tpm2_flushcontext missing in initramfs

---

src/luks/clevis-luks-common-functions.in

Function clevis_luks_check_valid_key_or_keyfile is
spending most of the boot time dedicated to unlock devices.
However, this function is always returning true for an
already encrypted device (normal call execution).
Parameterizing this function to avoid this check allows
decreasing boot time about 2 seconds per luks device

Improve boot performance by removing key check

---

src/clevis

When specifying 'clevis' command with no parameters,
different options should be printed without message
"Command 'clevis' is invalid"
Fixes #376

Avoid invalid message for clevis command

---

src/luks/clevis-luks-edit

This redirection is unnecessary and hides many interesting errors when rebinding
with clevis

luks-edit: remove unnecessary 2>/dev/null

---

README.md
src/luks/clevis-luks-unlockers.7.adoc

Hi,
with the changes from https://github.com/latchset/clevis/pull/211 and https://github.com/latchset/clevis/pull/252 networking is no longer automatically enabled during early boot. This PR adds a note about how to enable it.
Greetings
Klaas

Update README.md to include note about networking during boot

---

.github/workflows/install-dependencies
src/luks/clevis-luks-bind
src/luks/clevis-luks-bind.1.adoc
src/luks/clevis-luks-common-functions.in
src/luks/meson.build
src/luks/tests/bind-luks2-ext-token
src/luks/tests/meson.build
src/luks/tests/tests-common-functions.in

This change introduces new parameter "-e", that
allows specifying an existing token ID to avoid
having to provide an existing passphrase and
use an already configured LUKS2 token ID to read it

Add external token id parameter for existing passphrase

---

src/luks/clevis-luks-unlock
src/luks/clevis-luks-unlock.1.adoc
src/luks/tests/meson.build
src/luks/tests/unlock-arbitrary-parameter

Quick attempt to allow passing of arbitrary args to 'cryptsetup open' when unlocking volume.  Related to the discussion [here](https://github.com/latchset/clevis/issues/316).

passing args to 'cryptsetup open'

---

README.md

All references to "http" pin make no sense in README.md or other documentation, as "http" pin exists no more. They must be changed to "tang" pin. This commit changes this so that no more references to "http" pin exist.
Resolves: #423

Fix README.md to include "tang" pin

---

.github/workflows/spellcheck.yml
INSTALL.md
README.md

Changes proposed in this pull request:
- Added Language Tool
- Added Misspell check
Files Added
spellcheck.yaml @.github\workflows\
currently level is set to `warning` so that it doesnt stops the PR and CI will succeed with info shown as warning . Can be changed to `error` if required

Added language and misspell check for markdown files

---

src/initramfs-tools/scripts/local-bottom/clevis.in

The usage of `ps -l` is fragile and does not always return the expected set of columns. It differs even between several BusyBox versions and operating systems. Use `ps -o pid,ppid` to get the expected set of columns instead.
Also kill parent first before its children to prevent spawning another command from clevisloop itself.
Fixes #448

Fix killing of child process of clevisloop

---

.github/workflows/build.yml
.github/workflows/differential-shellcheck.yml
.github/workflows/spellcheck.yml

Upgrade version of checkout Github action
from v3 to v4, as v4 is based on Node20
Resolves: #451

Upgrade checkout version (v3->v4)

---

src/initramfs-tools/hooks/clevis.in
src/initramfs-tools/scripts/local-top/clevis.in

As mentioned in  #148 there seems to be a problem with the name resolution when using tang pin. If the URL to the server is not a plain IP, clevis is unable to contact tang. I could recreate this issue on Ubuntu 11. The changes in initramfs-tool hooks and scripts fixed it.
In my test setup i could only verify the changes with a DHCP server that hands out a single DNS server via IPv4 on a single interface. So the second IPv4 DNS, IPv6 DNS and multiple interfaces section in the code is only proofread and not tested.

Fix DNS resolution in initramfs

---

.github/workflows/install-dependencies
src/luks/tests/assume-yes
src/luks/tests/assume-yes-luks2
src/luks/tests/bind-binary-keyfile-luks1
src/luks/tests/bind-luks1-avoid-luksmeta-corruption
src/luks/tests/edit-tang-luks1
src/luks/tests/edit-tang-luks2
src/luks/tests/pass-tang-luks1
src/luks/tests/pass-tang-luks2
src/luks/tests/regen-inplace-luks1
src/luks/tests/regen-inplace-luks2
src/luks/tests/regen-not-inplace-luks1
src/luks/tests/regen-not-inplace-luks2
src/luks/tests/report-sss-luks1
src/luks/tests/report-sss-luks2
src/luks/tests/report-tang-luks1
src/luks/tests/report-tang-luks2
src/luks/tests/unlock-arbitrary-parameter
src/luks/tests/unlock-tang-luks1
src/luks/tests/unlock-tang-luks2
src/pins/tang/tests/default-thp-alg
src/pins/tang/tests/pin-tang
src/pins/tang/tests/tang-common-test-functions.in
src/pins/tang/tests/tang-validate-adv

There are currently two build [failures](https://github.com/latchset/clevis/actions/runs/8961382072/job/24608935028):
* build on fedora fails, because the `pw_dict.pwd` is missing:
```
{"payload": "eyJrZXlzIjogW3siYWxnIjogIkVDTVIiLCAiY3J2IjogIlAtNTIxIiwgImtleV9vcHMiOiBbImRlcml2ZUtleSJdLCAia3R5IjogIkVDIiwgIngiOiAiQVJJUHhCUEY5TzR1VnZ2d19IWjg3bW51c0xQd2JLYUNQN0tCSW51azA0Wk43X0JnQUVZRUdjcGZiZXdVU29XU0RkQXpKRnVjSFBmNzVaeWY4Rno5anAybiIsICJ5IjogIkFHeHFtYldLNFdZalN2SzBxbXF6VE9NT0RsTkZLV3BnVUxhYjlueDBSRlNTck4tb1JQazFMUUNQdDhQY3ZWb3BxSlNCVWMwc1hIcW4tVGVKLUtZMW43MmIifSwgeyJhbGciOiAiRVM1MTIiLCAiY3J2IjogIlAtNTIxIiwgImtleV9vcHMiOiBbInZlcmlmeSJdLCAia3R5IjogIkVDIiwgIngiOiAiQVdQRkdLVnZ5azVMX2N6SlZXUVA2b1N6LVhGRmpHeEFRY1NnLXRral9Kcjl0am9wUWFsSUZzRGlndHdkeG1kQm5mY1dVM1pxajZPYl9zd0xwZG5hR2o2NSIsICJ5IjogIkFBSl …
```

Fix 2 GitHub Actions issues

---

src/pins/tang/tests/tang-common-test-functions.in

The `port` argument is not used, so remove it. The `reuseaddr` flag is useless, we use fresh new port, we are not reusing any.
The second `reuseaddr` is cleaned-up in #488.

tang: clean-up unused variable, omit reuseaddr

---

src/pins/pkcs11/clevis-encrypt-pkcs11

When built under Debian-11, the following error appears:
```
++ echo secret
++ clevis decrypt
++ clevis encrypt pkcs11 '{"uri":"pkcs11:module-path=/usr/lib/softhsm/libsofthsm2.so?pin-value=123456","mechanism":"RSA-PKCS"}'
unable to load Public Key
Unable to encrypt JWK with PKCS#11 public key
```
Fix this by telling the key file format (DER) to OpenSSL.

pkcs11: provide key file format to openssl

---

src/luks/systemd/meson.build

This increases build compatibility between systems, like Debian 11 and Debian 12.

systemd: search for systemd-reply-password in dir specified by systemd

---

src/pins/tang/tests/tang-common-test-functions.in

The `socat` forwards HTTP request to a script and forwards whatever the script produces to the HTTP client. The `socat` in this configuration fails occasionally. When the script is finished and there is still something to be forwarded to it, the `socat` reports a broken pipe. Fix this by explicitly configuring the read and write ends, reading from the file and writing to /dev/null.
This fixes the following build test error:
```
+ clevis encrypt tang '{"url":"localhost:44157"}' -y
> 2024/10/05 14:46:51.000039424  length=82 from=0 to=81
GET /adv/ HTTP/1.1\r
Host: localhost:44157\r
User-Agent: curl/8.6.0\r
Accept: */*\r
\r
2024/10/05 14:46:51 socat[16880] E write(5, 0x55efa9173000, 82): Broken pipe
+ echo 'Error (do_test) response: /tmp/tmp.skxEYJGb28/cases/good-01'
Error (do_test) response: …
```

tang: allow reading full request by socat fake http server

---

src/pins/pkcs11/meson.build

Fixes the following error when building for Debian 11:
```
FAILED: src/pins/pkcs11/clevis-pkcs11-afunix-socket-unlock
cc  -o src/pins/pkcs11/clevis-pkcs11-afunix-socket-unlock src/pins/pkcs11/clevis-pkcs11-afunix-socket-unlock.p/clevis-pkcs11-afunix-socket-unlock.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,-z,relro -Wl,-z,now -g -O2 -ffile-prefix-map=/usr/src/clevis-21=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2
/usr/bin/ld: src/pins/pkcs11/clevis-pkcs11-afunix-socket-unlock.p/clevis-pkcs11-afunix-socket-unlock.c.o: in function `main':
./obj-x86_64-linux-gnu/../src/pins/pkcs11/clevis-pkcs11-afunix-socket-unlock.c:270: undefined reference to `pthread_create'
/usr/bin/ld: ./obj-x86_64-linux-gnu/../src/pins/pkcs11/clevis-pkcs11-afunix-socket-unlo …
```

pkcs11: add missing threads dependency

---

src/luks/dracut/clevis-pin-pkcs11/module-setup.sh.in

The check allows installation of all Dracut files together, as it is done with Debian packaging, so that it works even without having pkcs11 pin installed.

pkcs11: add Dracut install check

---

src/luks/dracut/clevis-pin-pkcs11/module-setup.sh.in
src/luks/systemd/clevis-luks-pkcs11-askpin.in
src/pins/pkcs11/clevis-pkcs11-afunix-socket-unlock.c
src/pins/pkcs11/clevis-pkcs11-common

Hot fix to sort out execution of dracut when no PKCS#11 device exists, no configuration has been performed in /etc/crypttab but, even in this case, empty device is prompted (when it should not)

PKCS#11 pin: fix dracut for unconfigured device

---

src/pins/tpm2/clevis-encrypt-tpm2

Clevis cleans the context regurarly from transient objects by invoking `tpm2_flushcontext -t`, but there is one case which Clevis omits. The `tpm2_createpolicy` command loads new session and this needs to be cleaned by a call to `tpm2_flushcontext -l`, see https://github.com/tpm2-software/tpm2-tools/issues/3427.
This is usually not an issue when resource manager is used (i.e. with `/dev/tpmrm0` device), but when raw TPM device `/dev/tpm0` or software TPM (swtpm) without resource manager is used, the usage of clevis (multiple calls are required) ends with the following error:
```
WARNING:esys:src/tss2-esys/api/Esys_StartAuthSession.c:390:Esys_StartAuthSession_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_StartAuthSession.c:136:Esys_StartAuthSession() Esys Finish ErrorCode …
```

tpm2: fix dangling loaded session after tpm2_createpolicy

---

src/pins/tpm2/clevis-encrypt-tpm2
src/pins/tpm2/clevis-encrypt-tpm2.1.adoc
src/pins/tpm2/pin-tpm2

The default is `sha1`, which is not always supported (it is legacy and optional for implementation). Make this more future-proof and use the first bank with non-empty set of PCRs, which is returned from TPM by `tpm2_getcap pcrs`.
The swtpm by default does not create sha1 bank, so this fixes usage with swtpm.

tpm2: use first PCR algorithm bank supported by TPM as default

---

src/pins/tang/tests/meson.build
src/pins/tang/tests/tang-common-test-functions.in

Groom references to deprecated tangd-update script

---

src/initramfs-tools/hooks/clevis.in

The path is the one used on Debian and Ubuntu, which should match
where initramfs-tools is used.

initramfs-tools: Copy a certificate bundle so curl can do https

---

src/luks/dracut/clevis/module-setup.sh.in

Dracut v103+ moved SystemD cryptsetup code into a separate module, so detect it and when found, use it.
Clevis units do not depend on `cryptsetup.target`, so do not install it. The target `cryptsetup.target` is installed by both [90systemd-cryptsetup][1] in v103+ and [01systemd-cryptsetup][2] in v105+, so there is no need to install it by Clevis.
Fixes: #493
Note: Tested with Dracut v102 (Fedora 40) and v103 (Fedora Rawhide).
[1]: https://github.com/dracut-ng/dracut-ng/blob/3fce598fb45aa5618cdf885eb48cf327104ffcb8/modules.d/90systemd-cryptsetup/module-setup.sh#L53
[2]: https://github.com/dracut-ng/dracut-ng/blob/a2669c447bd5e0406f55efcc8c9c58be89458b08/modules.d/01systemd-cryptsetup/module-setup.sh#L54

dracut: fix running with pre-v103 Dracut

---

.github/workflows/install-dependencies

This fixes build on Fedora 43 (Rawhide) with missing `systemd` and `awk`:
```
Failed to resolve the transaction:
Problem: systemd-257.2-17.fc42.i686 from rawhide has inferior architecture
- package device-mapper-1.02.204-3.fc42.x86_64 from rawhide requires systemd >= 256~rc1, but none of the providers can be installed
- problem with installed package
- installed package systemd-standalone-sysusers-257.2-17.fc42.x86_64 conflicts with systemd provided by systemd-257.2-17.fc42.x86_64 from rawhide
- package systemd-257.2-17.fc42.x86_64 from rawhide conflicts with systemd-standalone-sysusers provided by systemd-standalone-sysusers-257.2-17.fc42.x86_64 from rawhide
- package device-mapper-libs-1.02.204-3.fc42.x86_64 from rawhide requires device-mapper = 1.02.204-3.fc42, but none of the …
```

ci: fix fedora 43 (rawhide) build

---

src/luks/meson.build
src/pins/pkcs11/meson.build
src/pins/tang/meson.build

in a cross build, test cannot be run, as target and host is different, 
so we remove it if we are doing a cross build
-> this is RFC - if it can be resolved another way, let me know

 conditionally remove tests from cross build

---

README.md

clevis-pin-pkcs11 has been changed to retrieve
its whole dependencies (socat, openssl, ...)
so it is not necessary to install them manually

Remove dependencies and -y parameter

---

src/luks/dracut/clevis-pin-pkcs11/clevis-pkcs11-hook.sh.in
src/luks/dracut/clevis-pin-pkcs11/meson.build
src/luks/dracut/clevis-pin-pkcs11/module-setup.sh.in
src/luks/systemd/clevis-luks-pkcs11-askpass.in
src/luks/systemd/clevis-luks-pkcs11-askpass.service.in

should resolve error in dracut installing `clevis-luks-pkcs11-askpass` & `clevis-luks-pkcs11-askpin` for distros where `libexecdir` is configured elsewhere than `/usr/libexec` (Arch et. al.)

fix missing pkcs11 when libexecdir is configured
