latchset/clevis

src/clevis
Now listing whole command that clevis wanted to run
after potential recursion and binding
=> Made error verbose when invalid bin/arg  specified

src/clevis-decrypt, src/clevis-decrypt-http, src/clevis-decrypt-tang, src/clevis-decrypt-test, src/clevis-decrypt-tpm2, src/clevis-encrypt-http, src/clevis-encrypt-tang, src/clevis-encrypt-test, src/clevis-encrypt-tpm2, src/clevis-luks-bind, tests/pin-httpd
=> replaced 'cat' with '/bin/cat'

src/pins/tang/meson.build
=> Search for tang in libdir used by Ubuntu 18.04 packages

src/bash/clevis
- add support for completing -d (device) and -k (keyfile) arguments
- use command instead of which
- quote variables
- use -- with grep so that we don't run into issues when grepping for
something beginning with a dash
=> Improve bash completion

src/initramfs-tools/scripts/local-bottom/clevis.in
This is a proposal for https://github.com/latchset/clevis/issues/209
=> initramfs - fix iface name

README.md
Again, thank you for your time developing the tang/clevis system. Cheers
=> just correct some spelling

src/pins/tpm2/clevis-decrypt-tpm2, src/pins/tpm2/clevis-encrypt-tpm2, src/pins/tpm2/pin-tpm2
Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>
=> Jump forward to rewritten TPM2 pin if available

.travis/install, src/luks/clevis-luks-bind.in, src/pins/tang/meson.build, src/pins/tang/pin-tang
luks: improve error message when bind is given an invalid PIN
pins: update tang test so that it runs in all platforms
travis: install systemd in debian/ubuntu containers
=> Small fixes

src/initramfs-tools/hooks/clevis.in, src/initramfs-tools/scripts/local-top/clevis.in, src/luks/clevis-luks-bind.in, src/luks/clevis-luks-common-functions, src/luks/systemd/dracut/clevis/module-setup.sh.in
For background, see discussion commencing [here](https://github.com/latchset/clevis/pull/229#issuecomment-687253490).
=> Wait for dev in loop

src/luks/clevis-luks-common-functions, src/luks/tests/meson.build, src/luks/tests/unbind-unbound-slot-luks2, src/pins/tpm2/meson.build
Changes:
- tests: fix unbind unbound slot (LUKS2) test
- luks: remove temporary directory when clevis_luks_do_bind fails
- tests: increase timeout for some of the tests
- luks: avoid `head' usage in clevis luks common functions
=> Minor fixes and changes

src/initramfs-tools/hooks/clevis.in
=> Include TPM kernel modules in initram

src/luks/clevis-luks-pass, src/luks/clevis-luks-pass.1.adoc, src/luks/meson.build, src/luks/tests/meson.build, src/luks/tests/pass-tang-luks1, src/luks/tests/pass-tang-luks2
clevis luks pass returns the LUKS passphrase used for binding a
particular slot.
Usage:
clevis luks pass -d DEV -s SLT
Man page and tests added as well.
=> Add clevis luks pass command

src/luks/clevis-luks-bind, src/luks/clevis-luks-common-functions.in, src/luks/tests/bind-luks2, src/luks/tests/meson.build
@sergio-correia Here is the fix. I've tested it locally and added a test as we discussed.
=> Fix for -t option in clevis luks bind

src/luks/clevis-luks-bind, src/luks/clevis-luks-regen
* luks: make sure the configuration is valid JSON in clevis-luks-bind
* luks: fix use of return instead of exit in clevis-luks-regen
=> Minor updates/fixes

src/luks/clevis-luks-common-functions.in, src/luks/tests/bind-luks1-avoid-luksmeta-corruption, src/luks/tests/meson.build
=> Avoid luksmeta corruption on clevis bind

src/luks/clevis-luks-unlockers.7.adoc
=> Fix acronym (DHCP) to use capital letters

meson.build
=> Release clevis version 19

.github/workflows/build.yml
=> Fix Github actions by using latest ubuntu distro

README.md
=> Fix README.md to include correct sss example

.github/workflows/build.yml, .github/workflows/install-dependencies
=> Use quay.io version of Fedora Rawhide container

.github/workflows/build.yml
=> Upgrade version for checkout  Github action

.github/workflows/build.yml, .github/workflows/differential-shellcheck.yml
=> Avoid execution of Github actions for Markdown

README.md
=> Include manual compilation steps

meson.build
=> Release version 20

.github/workflows/install-dependencies
=> Ensure dnf builddep is installed in Fedora

meson.build
=> Release version 21

src/luks/clevis-luks-common-functions.in, src/luks/tests/bind-luks1, src/luks/tests/bind-luks2
=> Fix support for LUKS device with an empty password
